### ISSUE TITLE
[feature request] render to gif/png for sites that don't support svg embedding

### ISSUE THREAD

**Issue by cello-soul-termite** [MJaroslav/moe-counter-remade#1]
-

**Comment by MJaroslav** [comment]
It may not be relevant, but can you give an example of a site with this?

**Comment by ghost** [comment]
I was trying to use the counter in a MyBB forum signature, but that forum closed down meanwhile so oh well

**Comment by MJaroslav** [comment]
Anyway i'm add hard png render in https://github.com/MJaroslav/moe-counter-remade/commit/cbcfb7acbe6b56fb4812909477f65658cc7da2c0 but repl.it change their policy of hosting and this project required be selfhosted now (or you can use original counter).
